# Generated by Django 6.0.6 on 2026-07-31 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0006_doctornotificationsettings'),
        ('hospitals', '0003_alter_hospitalapplication_hospital_admin'),
        ('laboratory', '0003_alter_laborder_prescription'),
        ('medical_records', '0001_initial'),
        ('patients', '0005_patientsettings'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['patient'], name='medical_rec_patient_16738f_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['severity'], name='medical_rec_severit_9bc0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['recorded_at'], name='medical_rec_recorde_8a4946_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['medical_record'], name='medical_rec_medical_1bc7af_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_at'], name='medical_rec_uploade_ad4fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicdisease',
            index=models.Index(fields=['patient'], name='medical_rec_patient_fdea02_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicdisease',
            index=models.Index(fields=['disease'], name='medical_rec_disease_3485f4_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicdisease',
            index=models.Index(fields=['diagnosed_date'], name='medical_rec_diagnos_22d3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='chronicdisease',
            index=models.Index(fields=['is_active'], name='medical_rec_is_acti_3c5dde_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['medical_record'], name='medical_rec_medical_2c655d_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['scheduled_date'], name='medical_rec_schedul_a38f69_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='medical_rec_status_655452_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient'], name='medical_rec_patient_338240_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['doctor'], name='medical_rec_doctor__568b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['hospital'], name='medical_rec_hospita_9e41cd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['appointment'], name='medical_rec_appoint_900109_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['prescription'], name='medical_rec_prescri_f947cf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['lab_order'], name='medical_rec_lab_ord_aebf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['visit_date'], name='medical_rec_visit_d_b53313_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['status'], name='medical_rec_status_4e6ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='medical_rec_created_3a5a52_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['is_deleted'], name='medical_rec_is_dele_a3ee9c_idx'),
        ),
        migrations.AddIndex(
            model_name='pasthistory',
            index=models.Index(fields=['patient'], name='medical_rec_patient_ed985e_idx'),
        ),
        migrations.AddIndex(
            model_name='pasthistory',
            index=models.Index(fields=['recorded_at'], name='medical_rec_recorde_5976a5_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['patient'], name='medical_rec_patient_933cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['vaccine'], name='medical_rec_vaccine_1c7607_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccination',
            index=models.Index(fields=['administration_date'], name='medical_rec_adminis_5dc2ed_idx'),
        ),
    ]
