# Generated by Django 6.0.6 on 2026-07-23 03:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0002_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(db_index=True, help_text='Short code, e.g., CBC, LFT, TSH.', max_length=20, unique=True, verbose_name='Test Code')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Test Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the test.', verbose_name='Description')),
                ('normal_range', models.CharField(blank=True, help_text='e.g., "4.5–11.0 x10^3/µL" or "Male: 13.5–17.5 g/dL".', max_length=200, verbose_name='Normal Range')),
                ('unit', models.CharField(blank=True, help_text='e.g., mg/dL, µL, IU/L.', max_length=50, verbose_name='Unit')),
                ('sample_type', models.CharField(blank=True, help_text='e.g., Blood, Urine, Swab.', max_length=100, verbose_name='Sample Type')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of the test in Bangladeshi Taka.', max_digits=10, verbose_name='Price (BDT)')),
                ('preparation', models.TextField(blank=True, help_text='Special preparation required before the test.', verbose_name='Preparation Instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tests will not appear in dropdowns.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Laboratory Test',
                'verbose_name_plural': 'Laboratory Tests',
                'db_table': 'laboratory_test',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, help_text='Auto‑generated unique identifier (LAB-YYYYMMDD-XXXX).', max_length=20, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the lab technician.', verbose_name='Notes')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ordered Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
                ('appointment', models.ForeignKey(editable=False, help_text='Auto‑populated from the prescription.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='appointments.appointment', verbose_name='Appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('doctor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='doctors.doctor', verbose_name='Doctor')),
                ('hospital', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='hospitals.hospital', verbose_name='Hospital')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient', verbose_name='Patient')),
                ('prescription', models.OneToOneField(help_text='The prescription that generated this lab order.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_order', to='prescriptions.prescription', verbose_name='Prescription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'db_table': 'laboratory_laborder',
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for this test.', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder', verbose_name='Lab Order')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.laboratorytest', verbose_name='Laboratory Test')),
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
                'db_table': 'laboratory_laborderitem',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, help_text='Actual result value (e.g., "5.2", "Positive", "Normal").', verbose_name='Result')),
                ('interpretation', models.TextField(blank=True, help_text='Clinical interpretation (e.g., "Normal", "Abnormal").', verbose_name='Interpretation')),
                ('remarks', models.TextField(blank=True, help_text='Additional comments from the technician or pathologist.', verbose_name='Remarks')),
                ('report_file', models.FileField(blank=True, help_text='Upload PDF, JPEG, or PNG file (max 10 MB).', null=True, upload_to='laboratory/reports/%Y/%m/%d/', verbose_name='Report File')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Time when the result was verified.', null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.laborderitem', verbose_name='Order Item')),
                ('technician', models.ForeignKey(blank=True, help_text='User who entered the result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_technician', to=settings.AUTH_USER_MODEL, verbose_name='Technician')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Doctor or pathologist who verified the result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'db_table': 'laboratory_labresult',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories will not appear in dropdowns.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Test Category',
                'verbose_name_plural': 'Test Categories',
                'db_table': 'laboratory_testcategory',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='laboratory__name_ad6b0f_idx'), models.Index(fields=['is_active'], name='laboratory__is_acti_27cd9d_idx'), models.Index(fields=['deleted_at'], name='laboratory__deleted_380ab8_idx')],
            },
        ),
        migrations.AddField(
            model_name='laboratorytest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.testcategory', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['order_number'], name='laboratory__order_n_0aa245_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='laboratory__status_a16991_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'doctor', 'hospital'], name='laboratory__patient_143798_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['prescription'], name='laboratory__prescri_e99be3_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['deleted_at'], name='laboratory__deleted_92adbf_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordered_date'], name='laboratory__ordered_360ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderitem',
            index=models.Index(fields=['lab_order'], name='laboratory__lab_ord_12a09b_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderitem',
            index=models.Index(fields=['test'], name='laboratory__test_id_ae98d9_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderitem',
            index=models.Index(fields=['deleted_at'], name='laboratory__deleted_bb6cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['order_item'], name='laboratory__order_i_b05252_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['technician'], name='laboratory__technic_61aceb_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['verified_by'], name='laboratory__verifie_1531e7_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['deleted_at'], name='laboratory__deleted_92c25a_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['test_code'], name='laboratory__test_co_cb0cde_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['name'], name='laboratory__name_c4bb36_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['category', 'is_active'], name='laboratory__categor_49cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratorytest',
            index=models.Index(fields=['deleted_at'], name='laboratory__deleted_4a0dac_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratorytest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('test_code',), name='unique_active_test_code'),
        ),
    ]
