# Generated by Django 6.0.6 on 2026-07-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='appointment',
            field=models.ForeignKey(blank=True, editable=False, help_text='Auto‑populated from the prescription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='appointments.appointment', verbose_name='Appointment'),
        ),
    ]
