# Generated by Django 6.0.6 on 2026-07-30 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laborder_appointment'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='prescription',
            field=models.OneToOneField(blank=True, help_text='The prescription that generated this lab order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_order', to='prescriptions.prescription', verbose_name='Prescription'),
        ),
    ]
