# Generated by Django 6.0.6 on 2026-07-24 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='pharmacy_ca_slug_d1ac18_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='pharmacy_ca_is_acti_ada6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['medicine'], name='pharmacy_in_medicin_549f97_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_type'], name='pharmacy_in_transac_091744_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['created_at'], name='pharmacy_in_created_a9b705_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='pharmacy_me_categor_2a0502_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='pharmacy_me_is_acti_1c529c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiry_date'], name='pharmacy_me_expiry__807742_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['manufacturer'], name='pharmacy_me_manufac_58f6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['dosage_form'], name='pharmacy_me_dosage__6cc304_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['medicine_code'], name='pharmacy_me_medicin_181b43_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['barcode'], name='pharmacy_me_barcode_6df203_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase'], name='pharmacy_pu_purchas_e0e77b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['medicine'], name='pharmacy_pu_medicin_9538ef_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='pharmacy_pu_supplie_7c58fc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['purchase_date'], name='pharmacy_pu_purchas_1d9ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['payment_status'], name='pharmacy_pu_payment_b5f0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['purchase_number'], name='pharmacy_pu_purchas_bb17f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['patient'], name='pharmacy_sa_patient_799124_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='pharmacy_sa_sale_da_7996f6_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='pharmacy_sa_payment_9ef11d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pharmacist'], name='pharmacy_sa_pharmac_b808ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['invoice_number'], name='pharmacy_sa_invoice_1b97f4_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='pharmacy_sa_sale_id_68b1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['medicine'], name='pharmacy_sa_medicin_a1ba40_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone'], name='pharmacy_su_phone_2ac1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='pharmacy_su_email_dc6e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='pharmacy_su_is_acti_1de97d_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_unit_price_non_negative'),
        ),
    ]
