# Generated by Django 6.0.6 on 2026-08-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
        ('hospitals', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admins', to='hospitals.hospital'),
        ),
    ]
