# Generated by Django 6.0.6 on 2026-07-22 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Medical diagnosis based on the appointment.', verbose_name='Diagnosis')),
                ('symptoms', models.TextField(blank=True, help_text='Symptoms reported by the patient.', verbose_name='Symptoms')),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical observations and notes.', verbose_name='Clinical Notes')),
                ('advice', models.TextField(blank=True, help_text='General advice and recommendations for the patient.', verbose_name='Advice')),
                ('follow_up_date', models.DateField(blank=True, help_text='Scheduled follow‑up date, if any.', null=True, verbose_name='Follow-up Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('prescription_number', models.CharField(blank=True, help_text='Auto‑generated unique identifier (e.g., RX-202600001).', max_length=20, unique=True, verbose_name='Prescription Number')),
                ('doctor_signature', models.TextField(blank=True, help_text='Digital signature or verification token.', verbose_name='Doctor Signature')),
                ('qr_code', models.TextField(blank=True, help_text='QR code data for verification.', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
                ('appointment', models.OneToOneField(help_text='The completed appointment for this prescription.', on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment', verbose_name='Appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('doctor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor', verbose_name='Doctor')),
                ('hospital', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospitals.hospital', verbose_name='Hospital')),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_food', models.BooleanField(default=False, verbose_name='Before Food')),
                ('after_food', models.BooleanField(default=False, verbose_name='After Food')),
                ('morning', models.BooleanField(default=False, verbose_name='Morning')),
                ('afternoon', models.BooleanField(default=False, verbose_name='Afternoon')),
                ('night', models.BooleanField(default=False, verbose_name='Night')),
                ('medicine_name', models.CharField(help_text='Generic or brand name of the medicine.', max_length=255, verbose_name='Medicine Name')),
                ('dosage', models.CharField(help_text='e.g., 500 mg, 1 tablet, 5 ml.', max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(choices=[('once', 'Once daily'), ('twice', 'Twice daily'), ('three', 'Three times daily'), ('four', 'Four times daily'), ('as_needed', 'As needed'), ('other', 'Other')], default='once', max_length=20, verbose_name='Frequency')),
                ('duration', models.CharField(blank=True, help_text='e.g., 7 days, 2 weeks, as needed.', max_length=100, verbose_name='Duration')),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection', 'Injection'), ('inhalation', 'Inhalation'), ('suppository', 'Suppository'), ('other', 'Other')], default='oral', max_length=20, verbose_name='Route')),
                ('instruction', models.TextField(blank=True, help_text='Additional instructions for the patient.', verbose_name='Instruction')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the pharmacist or doctor.', verbose_name='Notes')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'prescriptions_medicine',
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='prescriptio_prescri_de216a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_940ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['appointment'], name='prescriptio_appoint_48b792_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'doctor', 'patient'], name='prescriptio_hospita_395c67_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['created_at'], name='prescriptio_created_1f24b5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['deleted_at'], name='prescriptio_deleted_82e507_idx'),
        ),
    ]
