# Generated by Django 6.0.6 on 2026-07-22 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment.', verbose_name='Appointment Date')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment.', verbose_name='Appointment Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, help_text='Reason for the appointment (optional).', verbose_name='Reason')),
                ('appointment_number', models.CharField(blank=True, help_text='Unique human-readable appointment number.', max_length=20, unique=True, verbose_name='Appointment Number')),
                ('token', models.CharField(blank=True, help_text='Hospital-specific token for the appointment.', max_length=50, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp.', null=True, verbose_name='Deleted At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Rescheduled At')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments_appointment',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
