# Generated by Django 6.0.6 on 2026-07-31 03:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Application ID')),
                ('application_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Application Number')),
                ('hospital_name', models.CharField(db_index=True, max_length=200, verbose_name='Hospital Name')),
                ('hospital_type', models.CharField(choices=[('general', 'General Hospital'), ('private', 'Private Hospital'), ('government', 'Government Hospital'), ('medical_college', 'Medical College Hospital'), ('clinic', 'Clinic'), ('diagnostic', 'Diagnostic Center'), ('dental', 'Dental Clinic'), ('eye', 'Eye Hospital'), ('mental_health', 'Mental Health Hospital'), ('ngo', 'NGO Hospital'), ('specialized', 'Specialized Hospital')], default='general', max_length=50, verbose_name='Hospital Type')),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='License Number')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('description', models.TextField(blank=True, verbose_name='Hospital Description')),
                ('hospital_email', models.EmailField(max_length=254, unique=True, verbose_name='Hospital Email')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g., 017XXXXXXXX)', regex='^01[3-9]\\d{8}$')], verbose_name='Phone Number')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g., 017XXXXXXXX)', regex='^01[3-9]\\d{8}$')], verbose_name='Emergency Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('division', models.CharField(max_length=50, verbose_name='Division')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('upazila', models.CharField(blank=True, max_length=50, verbose_name='Upazila')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Area')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('google_map_link', models.URLField(blank=True, verbose_name='Google Map Link')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('admin_name', models.CharField(max_length=150, verbose_name='Administrator Name')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Administrator Email')),
                ('admin_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g., 017XXXXXXXX)', regex='^01[3-9]\\d{8}$')], verbose_name='Administrator Phone')),
                ('admin_designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_applications/logos/', verbose_name='Hospital Logo')),
                ('trade_license', models.FileField(blank=True, null=True, upload_to='hospital_applications/documents/', verbose_name='Trade License')),
                ('hospital_license', models.FileField(blank=True, null=True, upload_to='hospital_applications/documents/', verbose_name='Hospital License')),
                ('govt_approval', models.FileField(blank=True, null=True, upload_to='hospital_applications/documents/', verbose_name='Government Approval')),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='hospital_applications/documents/', verbose_name='TIN Certificate')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='hospital_applications/documents/', verbose_name='Other Documents')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('need_more_info', 'Need More Information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('admin_remarks', models.TextField(blank=True, verbose_name='Admin Remarks')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('hospital_verified', models.BooleanField(default=False, verbose_name='Hospital Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('hospital_admin', models.ForeignKey(limit_choices_to={'role': 'hospital_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_applications', to=settings.AUTH_USER_MODEL, verbose_name='Hospital Admin')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Hospital Application',
                'verbose_name_plural': 'Hospital Applications',
                'db_table': 'hospitals_hospitalapplication',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='hospitals_h_status_8f00bf_idx'), models.Index(fields=['hospital_name'], name='hospitals_h_hospita_13c3f5_idx'), models.Index(fields=['license_number'], name='hospitals_h_license_9c7fff_idx'), models.Index(fields=['application_number'], name='hospitals_h_applica_c6ada2_idx'), models.Index(fields=['hospital_admin', 'created_at'], name='hospitals_h_hospita_b6192d_idx')],
            },
        ),
    ]
