# Generated by Django 6.0.6 on 2026-07-31 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalapplication',
            name='hospital_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_applications', to=settings.AUTH_USER_MODEL, verbose_name='Hospital Admin'),
        ),
    ]
