# Generated by Django 6.0.6 on 2026-08-02 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctornotificationsettings'),
        ('hospitals', '0003_alter_hospitalapplication_hospital_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('general_ward', 'General Ward'), ('private_cabin', 'Private Cabin'), ('vip_cabin', 'VIP Cabin'), ('icu', 'ICU'), ('nicu', 'NICU'), ('ccu', 'CCU'), ('operation_theater', 'Operation Theater'), ('emergency_room', 'Emergency Room'), ('consultation_room', 'Consultation Room'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('reception', 'Reception'), ('waiting_area', 'Waiting Area')], default='general_ward', max_length=30)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to='doctors.doctor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hospitals.hospitaldepartment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospitals.hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['department__name', 'room_number'],
                'unique_together': {('hospital', 'room_number')},
            },
        ),
    ]
