# Generated by Django 6.0.6 on 2026-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_address',
            field=models.TextField(blank=True, default='', help_text='Address of the primary contact'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_alt_phone',
            field=models.CharField(blank=True, default='', help_text='Alternative phone number for the primary contact', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_email',
            field=models.EmailField(blank=True, help_text='Email address of the primary contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_relationship',
            field=models.CharField(blank=True, default='', help_text='e.g., Spouse, Parent, Sibling', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_medical_decision_maker',
            field=models.BooleanField(default=False, help_text='Check if the primary contact is authorized to make emergency medical decisions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_ambulance',
            field=models.CharField(blank=True, default='', help_text='Preferred ambulance service provider', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_contact_email',
            field=models.EmailField(blank=True, help_text='Email address of the secondary contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of the secondary emergency contact', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number of the secondary contact', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_contact_relationship',
            field=models.CharField(blank=True, default='', help_text='Relationship of the secondary contact', max_length=50),
        ),
    ]
