# Generated by Django 6.0.6 on 2026-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_emergency_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], default='', help_text='Alcohol consumption', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated BMI', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diet_preference',
            field=models.CharField(blank=True, choices=[('non_veg', 'Non-vegetarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-free'), ('other', 'Other')], default='', help_text='Diet preference', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='exercise_frequency',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='', help_text='Exercise frequency', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], default='', help_text='Smoking status', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
