# Generated by Django 6.0.6 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_alcohol_consumption_patient_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cashless_facility',
            field=models.BooleanField(default=False, help_text='Does the policy offer cashless facility?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total coverage amount in BDT', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coverage_end_date',
            field=models.DateField(blank=True, help_text='End date of the insurance coverage', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coverage_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Coverage percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coverage_start_date',
            field=models.DateField(blank=True, help_text='Start date of the insurance coverage', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_coverage_available',
            field=models.BooleanField(default=False, help_text='Does the policy include emergency coverage?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_insurance',
            field=models.BooleanField(default=False, help_text='Does the patient have health insurance?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the insurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_plan',
            field=models.CharField(blank=True, default='', help_text='Name of the insurance plan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', help_text='Name of the insurance provider', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('corporate', 'Corporate'), ('student', 'Student'), ('other', 'Other')], default='', help_text='Type of insurance', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='member_id',
            field=models.CharField(blank=True, default='', help_text='Member ID / ID card number', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='policy_number',
            field=models.CharField(blank=True, default='', help_text='Insurance policy number', max_length=50),
        ),
    ]
