# Generated by Django 6.0.6 on 2026-07-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_cashless_facility_patient_coverage_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=2)),
                ('notify_appointments', models.BooleanField(default=True)),
                ('notify_prescriptions', models.BooleanField(default=True)),
                ('notify_laboratory', models.BooleanField(default=True)),
                ('notify_system', models.BooleanField(default=True)),
                ('show_mobile', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('hide_personal_info', models.BooleanField(default=False)),
                ('large_font', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='patients.patient')),
            ],
        ),
    ]
