# Generated by Django 6.0.6 on 2026-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=150)),
                ('national_id', models.CharField(default='0000000000', max_length=20, unique=True)),
                ('registration_number', models.CharField(default='000000', help_text='BMDC registration number', max_length=50, unique=True)),
                ('doctor_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('qualification', models.TextField(default='', help_text='Medical qualifications, degrees')),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee in BDT', max_digits=10)),
                ('available_days', models.CharField(blank=True, default='', help_text='e.g. Mon, Wed, Fri', max_length=100)),
                ('available_time_start', models.TimeField(blank=True, null=True)),
                ('available_time_end', models.TimeField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('bio', models.TextField(blank=True, default='', help_text='Short professional biography')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
    ]
