# Generated by Django 6.0.6 on 2026-07-29 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_appointments', models.PositiveIntegerField(default=10, help_text='Maximum appointments in this time slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availability',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Doctor is available for appointments'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Doctor has been verified by the system'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default='', help_text='The Django user account for this doctor. Required.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_doctor_user'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='unique_doctor_registration'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('national_id',), name='unique_doctor_national_id'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='doctors.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
