# Generated by Django 6.0.6 on 2026-07-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_fix_doctor_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10, verbose_name='Theme')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=5, verbose_name='Language')),
                ('timezone', models.CharField(choices=[('Asia/Dhaka', 'Asia/Dhaka'), ('UTC', 'UTC'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Dubai', 'Asia/Dubai')], default='Asia/Dhaka', max_length=30, verbose_name='Time Zone')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=10, verbose_name='Date Format')),
                ('time_format', models.CharField(choices=[('12', '12 Hour'), ('24', '24 Hour')], default='12', max_length=2, verbose_name='Time Format')),
                ('landing_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('appointments', 'Appointments'), ('prescriptions', 'Prescriptions'), ('laboratory', 'Laboratory'), ('notifications', 'Notifications')], default='dashboard', max_length=20, verbose_name='Landing Page')),
                ('items_per_page', models.IntegerField(choices=[(10, 'Ten'), (20, 'Twenty'), (50, 'Fifty'), (100, 'Hundred')], default=10, verbose_name='Items Per Page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Doctor Settings',
                'verbose_name_plural': 'Doctor Settings',
                'db_table': 'doctors_doctorsettings',
            },
        ),
    ]
