# Generated by Django 6.0.6 on 2026-07-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_enabled', models.BooleanField(default=True, verbose_name='Appointment Notifications')),
                ('appointment_new', models.BooleanField(default=True, verbose_name='New Appointment Request')),
                ('appointment_approved', models.BooleanField(default=True, verbose_name='Appointment Approved')),
                ('appointment_cancelled', models.BooleanField(default=True, verbose_name='Appointment Cancelled')),
                ('appointment_rescheduled', models.BooleanField(default=True, verbose_name='Appointment Rescheduled')),
                ('appointment_reminder', models.BooleanField(default=True, verbose_name='Appointment Reminder')),
                ('prescription_enabled', models.BooleanField(default=True, verbose_name='Prescription Notifications')),
                ('prescription_viewed', models.BooleanField(default=True, verbose_name='Prescription Viewed')),
                ('prescription_downloaded', models.BooleanField(default=True, verbose_name='Prescription Downloaded')),
                ('prescription_printed', models.BooleanField(default=True, verbose_name='Prescription Printed')),
                ('laboratory_enabled', models.BooleanField(default=True, verbose_name='Laboratory Notifications')),
                ('lab_request_created', models.BooleanField(default=True, verbose_name='Lab Request Created')),
                ('lab_sample_collected', models.BooleanField(default=True, verbose_name='Sample Collected')),
                ('lab_testing_started', models.BooleanField(default=True, verbose_name='Testing Started')),
                ('lab_report_ready', models.BooleanField(default=True, verbose_name='Report Ready')),
                ('lab_report_verified', models.BooleanField(default=True, verbose_name='Report Verified')),
                ('patient_enabled', models.BooleanField(default=True, verbose_name='Patient Notifications')),
                ('patient_assigned', models.BooleanField(default=True, verbose_name='New Patient Assigned')),
                ('followup_due', models.BooleanField(default=True, verbose_name='Follow-up Due')),
                ('system_enabled', models.BooleanField(default=True, verbose_name='System Notifications')),
                ('system_updates', models.BooleanField(default=True, verbose_name='System Updates')),
                ('system_maintenance', models.BooleanField(default=True, verbose_name='Maintenance')),
                ('security_alerts', models.BooleanField(default=True, verbose_name='Security Alerts')),
                ('new_features', models.BooleanField(default=True, verbose_name='New Features')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Notifications')),
                ('browser_enabled', models.BooleanField(default=True, verbose_name='Browser Notifications')),
                ('frequency', models.CharField(choices=[('immediate', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary')], default='immediate', max_length=10, verbose_name='Notification Frequency')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Enable Quiet Hours')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Doctor Notification Settings',
                'verbose_name_plural': 'Doctor Notification Settings',
                'db_table': 'doctors_doctornotificationsettings',
            },
        ),
    ]
