# Generated by Django 6.0.6 on 2026-07-22 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment_booked', 'Appointment Booked'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_approved', 'Appointment Approved'), ('appointment_completed', 'Appointment Completed'), ('patient_registered', 'Patient Registered'), ('doctor_added', 'Doctor Added'), ('hospital_added', 'Hospital Added'), ('prescription_generated', 'Prescription Generated'), ('lab_test_requested', 'Lab Test Requested'), ('lab_report_ready', 'Lab Report Ready'), ('medicine_dispensed', 'Medicine Dispensed'), ('medicine_low_stock', 'Medicine Low Stock'), ('revenue_alert', 'Revenue Alert'), ('system_notification', 'System Notification'), ('account_notification', 'Account Notification')], default='system_notification', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g. 'fas fa-bell'", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Tailwind color class, e.g. 'text-blue-400'", max_length=20)),
                ('url', models.CharField(blank=True, help_text='Relative URL to redirect when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
